services:
  # Статический клиент (Vite)
  - type: web
    name: collabo-color-client
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # WebSocket сервер (Node.js)
  - type: web
    name: collabo-color-server
    runtime: node
    rootDir: ./server
    buildCommand: npm install && tsc
    startCommand: node server.js
    healthCheckPath: /